### ISSUE TITLE
Rich editor (bold, italic and other inner nodes) spellcheck bug

### ISSUE THREAD

**Issue by maxmert** [sereneinserenade/tiptap-languagetool#2]
Hey mate! Thanks for the plugin. Currently, I'm refactoring it for my internal needs, I don't want any side effects to be handled inside the plugin. It seems like there is a bug in the algorithm:

if you mark a selection with bold (or any other), it will mark the next word as a misspelling. As in the case below, it thinks that the next word always should start with a capital letter. I think (and to be honest I didn't have any time to investigate yet), the problem is that you are trying to check not the entire block, but just part of it. Would really appreciate some help here:

<img width="929" alt="Screenshot 2022-05-20 at 21 20 06" src="https://user-images.githubusercontent.com/864232/169597227-2ea9f1a1-12ef-4ad7-a8d8-1d27a5272187.png">

**Comment by sereneinserenade** [comment]
I think this might be an issue on the LanguageTool side and not our side. However, will look into it when I have some time. Thanks for reporting!

**Comment by sereneinserenade** [comment]
Hey @maxmert, again thanks for reporting! This was an issue in algorithm.

I've fixed the issue, will be updating the repo soon with fix ⚡

**Comment by sereneinserenade** [comment]
@maxmert it's fixed.

**Comment by AnibalPal** [comment]
Hello, was this also solved in the js version of this plugin? I am having this issue.

Thanks in advance.

**Comment by AnibalPal** [comment]
Ended up fixing it myself, had to change the ts code to js.
